Only call #publish on a tweet if there is one to publish
Sometimes no new tweets are available for publishing. This did cause
errors to be raised that caused noise in our cronjob and its mailer.

```
rake aborted!
NoMethodError: undefined method `publish' for nil:NilClass
/app/app/services/tweet_service.rb:5:in `publish_when_due'
/app/lib/tasks/twitter.rake:5:in `block (2 levels) in <main>'
```

The safety operator should ensure that #publish is now only called on a
tweet if `Tweet.next` does not return `nil`.